### ISSUE TITLE
Error when building docker image

### ISSUE THREAD

**Issue by ando01** [caglar10ur/elk-usg#1]
When I run this command: `docker build -t elk-geoip ~/elk-usg/geoip/ `

I get an error during the plugin installation. Here is the output:

```
Step 4/4 : RUN CONF_DIR=/etc/elasticsearch gosu elasticsearch bin/elasticsearch-plugin                      install ingest-geoip
 ---> Running in 2ef7c5944934
-> Downloading ingest-geoip from elastic
[=================================================] 100%  
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@     WARNING: plugin requires additional permissions     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
* java.lang.RuntimePermission accessDeclaredMembers
* java.lang.reflect.ReflectPermission suppressAccessChecks
See http://docs.oracle.com/javase/8/docs/technotes/guides/security/permissions.html
for descriptions of what these permissions allow and the associated risks.

Exception in thread "main" java.lang.IllegalStateException: unable to read from standard input;          is standard input open and a tty attached?
        at org.elasticsearch.cli.Terminal$SystemTerminal.readText(Terminal.java:173)
        at org.elasticsearch.plugins.PluginSecurity.prompt(PluginSecurity.java:74)
        at org.elasticsearch.plugins.PluginSecurity.confirmPolicyExceptions(PluginSecurity.java:         67)
        at org.elasticsearch.plugins.InstallPluginCommand.installPlugin(InstallPluginCommand.jav         a:801)
        at org.elasticsearch.plugins.InstallPluginCommand.install(InstallPluginCommand.java:775)
        at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:231)
        at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:216)
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86         )
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)
        at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:77)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)
        at org.elasticsearch.cli.Command.main(Command.java:90)
        at org.elasticsearch.plugins.PluginCli.main(PluginCli.java:47)
The command '/bin/sh -c CONF_DIR=/etc/elasticsearch gosu elasticsearch bin/elasticsearch-plugin                      install ingest-geoip' returned a non-zero code: 1
```

**Comment by caglar10ur** [comment]
TBH its been a while since I build this :) I'll try to go over the README.md from scratch and files and fix them as needed (and let you know). Thanks for the report!
